#!/bin/bash
if ! (which python3 >/dev/null && python3 --version | grep ' 3.' >/dev/null); then
  echo "You must have python 3 installed to run this."
  exit 1
fi

pushd $(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd) >/dev/null

./SETMEUP
npm start >/dev/null

popd >/dev/null
