#!/bin/bash
if ! (which npm >/dev/null && npm --version | egrep '^9.6.7' >/dev/null); then
  echo "You must have npm 9.6.7 installed and in your PATH to run this."
  exit 1
fi

pushd $(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd) >/dev/null

output=$(npm ls 2>&1)
if [ $?==1 ]; then
  if [[ "$output" == *"UNMET DEPENDENCY electron@^36.2.0"* ]]; then
    npm install >/dev/null 2>&1
    sudo chown root:root node_modules/electron/dist/chrome-sandbox
    sudo chmod 4755 node_modules/electron/dist/chrome-sandbox
  fi
fi

popd >/dev/null
